### ISSUE TITLE
Imports broken in new project till I run first preview

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#1141]
If I create a project with the editor and dive straight into the code, I'll see that all the code is underlined in red, and it won't like any snippets I paste from the docs. This makes for a very confusing first experience.

![Image](https://github.com/user-attachments/assets/bd815f6c-327f-4906-bf69-74f886d33de1)

If I run a preview of my scene before I do this, then it's all fine. But maybe I didn't have any need to do this yet, so it will all feel broken.

Looks like when we run a preview, we're installing some dependencies. We should do that earlier, probably at the moment of creating the new project.

**Comment by nicoecheza** [comment]
The installation of dependencies was moved to the "preview" for faster inspector init time (since scene deps are not needed for running the inspector). Maybe we can install them in the back without waiting for them while the user is in the inspector, instead of doing it when the user clicks the "preview" button. What do you think? @nearnshaw @cazala

**Comment by cazala** [comment]
Sounds good to me, we can spawn the `npm install` after the scene is created without awaiting for it. Or have the `npm install` as a separate IPC and trigger it from the UI if we want to have more control or be aware if the process was successful or not.
