### ISSUE TITLE
review cli dependencies

### ISSUE THREAD

**Issue by gonpombo8** [decentraland/sdk#186]
`npm i -g decentraland` takes too long.
- [ ] Review if there are some dependencies that we are not using, 
- [ ] Update deprecated dependencies

**Comment by juanigallo** [comment]
Tried to update all package versions. Patches and minor versions worked without any problem.

Mayor versions throws some compilations issues that are easy to solve but it also breaks almost all the tests

<img width="1518" alt="image" src="https://user-images.githubusercontent.com/4969737/156510209-afbb8487-e2a7-497a-865d-b5028114646d.png">

<img width="242" alt="image" src="https://user-images.githubusercontent.com/4969737/156510274-d5dc99a5-6d5d-4ba4-aecf-76598a0f9919.png">

I will not create a PR for that part of this issue because I think that is a core feature and I'm not familiarized with the project. However, I'm leaving the comment so you can take advantage of the triage I did
