### ISSUE TITLE
Discussion: Component serialization of default values

### ISSUE THREAD

**Issue by menduz** [decentraland/sdk#340]
By default, protocol buffers don't serialize default values, e.g. bool=false, int=0, float=0.0, string="" are not serialized in the buffer of the message.

That renders two problems:
1. Extension of components: as time passes, components may receive new properties. But everybody must ensure that those properties' default values are the default values of the datatype, i.e. `int newGlowProperty=0;`, on the contrary, if the default value of that property is `1`, then older (deployed) versions of the component will stop working as intended because the renderer or any other component will assume the components had `1`, even though those versions didn't include the `newGlowProperty`
2. The initial version of the components MAY include default values, like the transform component `{position={0,0,0}, scale={1,1,1}}`. Once those components are shipped, the default values can't change if the values are not serialized, but they MAY change if a new version of the `component.identity()` is shipped.

**Comment by Suduck** [comment]
One possible solution is to make an abstraction layer on the user that then we convert to the current implementation.

An example with the AudioSource:

Right now we need to specify these attributes to make an Audio Source

`  sdk.AudioSource.create(myEntity,{
    audioClipUrl: "finalChest.mp3", 
    loop: true, 
    pitch: 1, 
    playedAtTimestamp: 0, 
    playing: true, 
    volume: 1
  })`

For the volume and pitch, we will need to have the default value of 1. So we create another class that will be the component for the final user. ( Take into account that for this example the Wrapper name is used to have a better understanding, but the name for the user will be AudioSource and we will have another name)


`  sdk.AudioSourceWrapper.create(myEntity,{
    audioClipUrl: "finalChest.mp3", 
  })`

This class will set the default value to 1 to pitch and volume in the `create ` function.

For the class that will be serialized over the wire, we invert the default

`  sdk.AudioSourceSerializer.create(myEntity,{
    audioClipUrl: "finalChest.mp3", 
    notLoop: false, 
    invertedPitch: 0, 
    playedAtTimestamp: 0, 
    notPlaying: false, 
    invertedVolume: 0
  })`


So when we are doing a deploy or using `dcl start` we do the following conversion ( this will happen internally, the user won't noticed this)


`  let audioSourceWrapper = sdk.AudioSourceWrapper.create(myEntity,{
    audioClipUrl: "finalChest.mp3", 
    volume: 1
  })
  
  let audioSourceSerializer = sdk.AudioSourceSerializer.create(myEntity,{
    audioClipUrl: "finalChest.mp3", 
    notLoop: false, 
    invertedPitch: 0, 
    playedAtTimestamp: 0, 
    notPlaying: false, 
    invertedVolume: 0
  })

audioSourceSerializer.invertedVolume = 1 - audioSourceWrapper.Volume
audioSourceSerializer.invertedPitch= 1 - audioSourceWrapper.Pitch
audioSourceSerializer.notLoop=  !audioSourceWrapper.Loop
  `
This way, if you set the volume to 1, it won't be serialized over the wire, but the user still can use the Volume with a default value of 1

Another good thing that we will introduce this, is that we could add functions like `Play()`  that internal just change the notPlaying attribute, or  `PlaySchedule()` that internal will set the `playedAtTimestamp` so this way, we don't expose the playedAtTimestamp attribute to the user since it can cause confusion

**Comment by leanmendoza** [comment]
@Suduck 
Good, I deeply read the proposal and I think it's OK.
I'd like to extend it exposing the pros and cons.

Definitely a pros: 
- We wouldn't have to change anything about the protocol.

With the next considerations:
- All fields should be defined by how its default value would be as you mention. `withoutCollision`, `hidden`, etc. 
The implementation in the renderer-side shouldn't have extra work, because when the serializer/deserializer processes you take the field description as is, with regular fields, the steps following would be the same. e.g.:
```proto
message BoxShape {
    bool withoutCollision = 1;
    bool hiden = 2;
}
``` 
No matter which means the field, the functionality must respect the description itself.

If you have a more complex data, the handlering becames more complex too. For example, a default color as `0xcccccc` (I take a material field of ecs6). We should be totally explicit in the proto definitions, so the requirement description propagates to the generated code.

```
// file: components/definitions/common/Color3.proto
// This message is a common one with all components
message Color3 {
    float r = 1;
    float g = 2;
    float b = 3;
}
```

```
// file: components/definitions/BoxShape.proto
import "common/Color3.proto";
message BoxShape {
    //....

    /**
    /* The default value is 0xCCCCCC
    /*   in the wire, this goes as 0x000000
   /*  So, the swap is 0xCCCCCC <=> 0x000000
    Color3 diffuseColor = 5;
}
```

In this way, the renderer-side has to handler this swap, if it receives a black color, it should to change to the default and viceversa.

```csharp
class BoxShape {
    private static DefaultDiffuseColor = new Color3(0.8, 0.8, 0.8);

    public Color3 diffuseColor;
    public BoxShape(PBBoxShape shape) {
        if (shape.diffuseColor == DefaultDiffuseColor){
            diffuseColor = new Color();
        } else if (shape.diffuseColor == (new Color())) {
            diffuseColor = DefaultDiffuseColor;
        }
    }
}
```

and the creator tool side, the EcsType should be written and not generated.

```ts
const defaultDiffuseColor = { r: 0.8, g: 0.8, b: 0.8 }
const defaultProtoColor3 = { r: 0, g: 0, b: 0 }
export type WrappedBoxShape {
      //....
     Color3 diffuseColor;
}

const wrapper = {
    toPB(value: WrappedBoxShape) : PBBoxShape {

    },
    fromPB(value: PBBoxShape): WrappedBoxShape {
        if (shape.diffuseColor == defaultProtoColor3 ){
            value.diffuseColor = defaultDiffuseColor;
        } else if (shape.diffuseColor == Color3()) {
            value.diffuseColor = defaultProtoColor3;
        }
   }
}

export const BoxShape: EcsType<WrappedBoxShape> = {
  serialize(value: WrappedBoxShape, builder: ByteBuffer): void {

    
    const writer = PBBoxShape.encode(wrapper.toPB(value))
    const buffer = new Uint8Array(writer.finish(), 0, writer.len)
    builder.writeBuffer(buffer)
  },
  deserialize(reader: WrappedBoxShape): PBBoxShape {
    const buf = reader.readBuffer()
    return PBBoxShape.decode(buf, buf.length)
  },
  create() : WrappedBoxShape {
       return {
// ....
           diffuseColor: defaultDiffuseColor
       }
  }
}


```

The clearly disadvantage of this is the maintenance, and the complexity scales enormously with the complexity of the component. I can't see right now if can exists  helpers to make it easier.  Other implementations of protocol will need to handler all the conditions and the components would need a complete documentation to handler each one.

For example, instead of arbitrary inverted volume, you can swap the 0 to 1. So thinking aloud, the swap value would be a common behaviour.
