### ISSUE TITLE
Consider renaming some packages

### ISSUE THREAD

**Issue by eordano** [decentraland/sdk#584]
Taking a look at `js-sdk-toolchain`, it look like some packages are unfortunately named, referencing what they "use", not what they "do":

* `@dcl/rollup` uses internally `rollup`, but it might be better to name it `@dcl/scene-bundler` or similar, using a name that refers to what is this useful for. Also, could we rename the folder to match the name of the package?
* I'm completely blind as to what `@dcl/crdt` does. I know what a CRDT is, but this looks like some netcode implementation. Wouldn't it be better to call this `@dcl/scene-synchronization` or `@dcl/net-reconciler`?
* `@dcl/ecs` might be better described as `@dcl/scene-api`, as this is the API exposed to render scenes, or simply `@dcl/scene`. `@dcl/scenes-engine` could be an option as well.

**Comment by gonpombo8** [comment]
I agree with this approach but I think that what the "use" has useful information in some cases.
- @dcl/scene-bundler instead of @dcl/rollup LGTM
- @dcl/crdt has the data structure and the function that provides the conflict resolution. So i don't think it should be renamed, its quite simple this package. There is no scene sync here, its a library that provides a function and updates an internal store.
- @dcl/ecs provides the ECS architecture, and we talk a looot about the ECS in our docs. Maybe ecs-engine-api or something related, i know we are talking about what it "uses" here but i found it useful in this case IMO. 

All the js-sdk-toolchain packages here had some relation to the scenes so naming scene-something to every package seems redundant for me.
