### ISSUE TITLE
Animations from scene not synced to other players

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#920]
This was reported from Dappcraft

When playing an emote triggered by the scene with `triggerEmote({ predefinedEmote: this.currentEmote });` I see my avatar run the animation, but other players don't see me do it

In the same tests, players were able to manually play emotes themselves and others could see those, but not the ones triggered by the scene

This issue happens both with the old "triggerEmote" that runs predefined emotes and with the "triggerSceneEmote" that runs custom emotes.

**Comment by Dolper** [comment]
Hey! 

SDK6 example: https://drive.google.com/file/d/1NTaFKAeAMrSNmgLvTCMZJR7JkCvIkwiJ/view?usp=sharing

SDK7 triggerSceneEmote: https://drive.google.com/file/d/1XFGFwubJZjW1DCst4BHjc4eJ_7pzRGI0/view?usp=sharing

The same issue with triggerSceneEmote and triggerEmote

Sometimes synchronization works, but rarely. Most of the time, it doesn't work.

**Comment by Dolper** [comment]
Test with both methods: https://drive.google.com/file/d/1YKqqJi9qvevdQiCDtqa5Jp-syoruLByD/view?usp=sharing

**Comment by Dolper** [comment]
We've figured out what the problem is. The bug occurs when you start an emote right after the avatar has stopped. Since other players see the avatar's movements with a slight delay, playing the emote gets interrupted. A workaround for this bug is to not start emotes immediately after the avatar stops moving but with a slight delay instead. This way, synchronization happens correctly. It's worth noting that this is just our hypothesis. In SDK 6, there was no such issue, but this bug doesn't seem important now, as there's a workaround.

**Comment by nearnshaw** [comment]
Closing this, as there are workarounds, and it shouldn't be a problem in explorer alpha
